@backend_HostAddress = http://localhost:5234

### Тест сервера
GET {{backend_HostAddress}}/ping  

### Регистрация нового пользователя
# Создаёт нового пользователя с именем, email и паролем
POST {{backend_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "name": "test1",
  "mail": "test1@example.com",
  "password": "123456",
  "avatarUrl": "https://i.pinimg.com/originals/d6/7c/74/d67c74e8c73a7c31005702fbe3a0b46a.jpg"
}

### Неуспешный вход (неверные учетные данные)
# Проверяет случай с несуществующим пользователем или неверным паролем
POST {{backend_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "mail": "aaa@example.com",
  "password": "wrongpassword"
}

### Успешный вход
# Предполагается, что пользователь уже зарегистрирован через предыдущий запрос
POST {{backend_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "mail": "test1@example.com",
  "password": "123456"
}

### Создание нового задания 1
POST {{backend_HostAddress}}/api/task
Content-Type: application/json

{
    "title": "Найти достопримечательность",
    "description": "Посетить и сфотографировать достопримечательность города",
    "difficulty": 1,
    "latitude": 55.7558,
    "longitude": 37.6173
}

### Создание нового задания 2
POST {{backend_HostAddress}}/api/task
Content-Type: application/json

{
    "title": "Найти лес",
    "description": "Посетить и сфотографировать лес",
    "difficulty": 0,
    "latitude": 54.7558,
    "longitude": 38.6173
}

### Получение всех заданий
GET {{backend_HostAddress}}/api/task

### Получение задания по ID
GET {{backend_HostAddress}}/api/task/1

### Получение всех отправок заданий пользователя
GET {{backend_HostAddress}}/api/task/user/1/submissions

### Начало выполнения задания
POST {{backend_HostAddress}}/api/task/start
Content-Type: application/json

{
    "userId": 1,
    "taskId": 1
}

### Завершение задания
POST {{backend_HostAddress}}/api/task/complete
Content-Type: application/json

{
    "userId": 1,
    "taskId": 1,
    "photoUrl": "https://example.com/photo.jpg",
    "description": "Отличное задание! Удалось посетить все места."
}

### Получение заданий пользователя с информацией о статусе
GET {{backend_HostAddress}}/api/task/user/1/tasks

### Получение ID заданий пользователя
GET {{backend_HostAddress}}/api/task/user/1/task-ids

### Получение ленты новостей
GET {{backend_HostAddress}}/api/task/news

### Получение конкретного поста
GET {{backend_HostAddress}}/api/post/1

### Добавление комментария к посту
POST {{backend_HostAddress}}/api/post/1/comment
Content-Type: application/json

{
    "userId": 1,
    "text": "Отличное фото!"
}

### Лайк поста
POST {{backend_HostAddress}}/api/post/1/like

### Создание достижения "Первые шаги"
POST {{backend_HostAddress}}/api/achievement
Content-Type: application/json

{
    "name": "Первые шаги",
    "points": 100
}

### Получение достижений пользователя
GET {{backend_HostAddress}}/api/achievement/user/1