@backend_HostAddress = http://localhost:5234

### Тест сервера
GET {{backend_HostAddress}}/ping  

### Регистрация нового пользователя
# Создаёт нового пользователя с именем, email и паролем
POST {{backend_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "name": "test1",
  "mail": "test1@example.com",
  "password": "123456"
}

### Неуспешный вход (неверные учетные данные)
# Проверяет случай с несуществующим пользователем или неверным паролем
POST {{backend_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "mail": "aaa@example.com",
  "password": "wrongpassword"
}

### Успешный вход
# Предполагается, что пользователь уже зарегистрирован через предыдущий запрос
POST {{backend_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "mail": "test1@example.com",
  "password": "123456"
}

### Создание первого задания
POST {{backend_HostAddress}}/api/task
Content-Type: application/json

{
    "title": "Сбор мусора в парке",
    "description": "Соберите мусор в центральном парке города",
    "difficulty": 0,
    "latitude": 55.7558,
    "longitude": 37.6173
}

### Создание второго задания
POST {{backend_HostAddress}}/api/task
Content-Type: application/json

{
    "title": "Посадка деревьев",
    "description": "Посадите 5 саженцев деревьев в городском сквере",
    "difficulty": 1,
    "latitude": 55.7500,
    "longitude": 37.6000
}

### Создание третьего задания
POST {{backend_HostAddress}}/api/task
Content-Type: application/json

{
    "title": "Очистка реки",
    "description": "Помогите очистить берег реки от мусора",
    "difficulty": 2,
    "latitude": 55.7600,
    "longitude": 37.6200
}

### Получение списка всех заданий
GET {{backend_HostAddress}}/api/task